import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../Components/Header';
import Hero from '../Components/Hero';
import { Toaster } from "react-hot-toast";
import { TimerProvider } from '../Components/TimerContext';



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
        <audio >
  <source src="../public/assets/TickSound.mp3" type="audio/mp3" />
  Your browser does not support the audio element.
</audio>
      </Head>

  

         <Hero />
    
  
     <Toaster
        toastOptions={{
          className: '',
          style: {
            background: 'linear-gradient(0deg, #1A2B68, #323095)',
            border: '1px solid white',
            
            color: 'white',
           width: 'fit-content'
          },
        }} />
       
    </div>
  );
};

export default Home;
